! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
! 
! HISTORY
! 
!   $XConsortium: formDia.msg /main/7 1995/07/13 20:45:20 drk $
!OSF/Motif: @(#)formDia.msg	3.2  92/01/31
!
!  
!  	THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED
!  AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE AND
!  WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR
!  ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE
!  AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE
!  SOFTWARE IS HEREBY TRANSFERRED.
!  
!  	THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT
!  NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY OPEN SOFTWARE
!  
!  
!  
!  
!  
!  
!  
!  
!  
! DEC is a registered trademark of Digital Equipment Corporation
! DIGITAL is a registered trademark of Digital Equipment Corporation
!
 value
        message : "This is a FormDialog with the following\ncharcteristics:\n\n" &
"   - width is 250\n   - height is 250\n   - background is b" &
"lue\n   - dialogTitle is The Form Dialog\n" &
"   - The form has six PushButtons.\n   - Callbacks are ON for all.\n" &
"   - PushButton1 is attached to form on\n     the BOTTOM, LEFT, and RIGHT.\n" &
"   - PushButton2 is attached to form on\n     the RIGHT and LEFT, and attached\n     to PB1 on the bottom.\n" &
"     rightOffset and leftOffset is 100\n" &
"   - PushButton3 is attached to form on\n     the RIGHT, attached to PB2 on the\n     BOTTOM, attached to PB5 on the TOP.\n" &
"   - PushButton4 is attached to form on\n     the LEFT, attached to PB2 on the\n     BOTTOM, attached to PB5 on the TOP.\n" &
"   - PushButton5 is attached to form on\n     the RIGHT and LEFT, and attached to\n     PB6 on the TOP.\n" &
"     rightOffset and leftOffset is 100\n" &
"   - PushButton6 is attached to form on\n     the TOP, RIGHT, and LEFT.\n" &
	"\n\nAll other resources are set by default.\n";
