! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
! 
! HISTORY
! 
!   $XConsortium: pulldown2.msg /main/4 1995/07/13 20:50:56 drk $
!  

! 
!  Created by RAS Group for HaL Computers.  Based on software by OSF, Inc.
!
 value
        message : "This is a pulldownMenu with\nthe following characteristics:\n\n" &
"   - the PulldownMenu is asscociated\n     with a MenuBar." &
" This\n     PulldownMenu has two pushbuttons;\n     a separatorGadget and a\n     togglebutton\n" &
"   - shadowThickness is 15\n   - marginWidth, marginHeight are 10\n" &
"   - foreground is black\n   - background is forestgreen\n" &
"   - entryAlignment is \n     XmALIGNMENT_CENTER\n   - spacing is 5\n" &
"   - map and unmap Callbacks are ON\n   - Callbacks are on for the\n     pushbuttons and togglebuttons\n" &
"\nAll other resources are set by default.\n";

