! 
! Motif
!
! Copyright (c) 1987-2012, The Open Group. All rights reserved.
!
! These libraries and programs are free software; you can
! redistribute them and/or modify them under the terms of the GNU
! Lesser General Public License as published by the Free Software
! Foundation; either version 2 of the License, or (at your option)
! any later version.
!
! These libraries and programs are distributed in the hope that
! they will be useful, but WITHOUT ANY WARRANTY; without even the
! implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
! PURPOSE. See the GNU Lesser General Public License for more
! details.
!
! You should have received a copy of the GNU Lesser General Public
! License along with these librararies and programs; if not, write
! to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
! Floor, Boston, MA 02110-1301 USA
! 
! 
! HISTORY
! 
!   $XConsortium: radioBox.msg /main/8 1995/07/13 20:51:31 drk $
!OSF/Motif: @(#)radioBox.msg	3.2  92/01/31
!
!  
!  	THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED
!  AND COPIED ONLY IN ACCORDANCE WITH THE TERMS OF SUCH LICENSE AND
!  WITH THE INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR
!  ANY OTHER COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE
!  AVAILABLE TO ANY OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF THE
!  SOFTWARE IS HEREBY TRANSFERRED.
!  
!  	THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT
!  NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY OPEN SOFTWARE
!  
!  
!  
!  
!  
!  
!  
!  
!  
! DEC is a registered trademark of Digital Equipment Corporation
! DIGITAL is a registered trademark of Digital Equipment Corporation
!
 value
        message : "This is a radioBox with the following\ncharacteristics:\n\n" &
"   - The radioBox has five children,\n     4 toggleButtonGadgets and 1 ToggleButton\n   - ValueChangedCallbacks are ON\n" &
"     for all toggleButtons\n   - height and width are 200\n   - borderWidth is 4\n   - background is cadetblue\n" &
"   - marginHeight, marginWidth are 10\n   - numColumns are 2\n   - packing is XmPACK_COLUMN\n" &
"   - spacing is 10\n   - entryAlignment is\n     XmALIGNMENT_CENTER\n   - entryCallback is ON\n\n" &
"   NOTE: The Toggle buttons valueChanged\n   callbacks will not come out. They\n   are vectored to entryCallback.\n\n" &
"All other resources are set by default.\n";
