.ta 8n 16n 24n 32n 40n 48n 56n 64n 72n 
.TH "XmCreateMultiList" "library call"
.SH "NAME"
\fBXmCreateMultiList\fP \(em The MultiList widget creation function
.iX "XmCreateMultiList"
.iX "creation functions" "XmCreateMultiList"
.SH "SYNOPSIS"
.PP
.nf
#include <Xm/MultiList\&.h>
\fBWidget \fBXmCreateMultiList\fP\fR(
\fBWidget \fBparent\fR\fR,
\fBString \fBname\fR\fR,
\fBArgList \fBarglist\fR\fR,
\fBCardinal \fBargcount\fR\fR);
.fi
.SH "DESCRIPTION"
.PP
\fBXmCreateMultiList\fP creates an instance of a MultiList widget and
returns the associated widget ID\&.
.IP "\fIparent\fP" 10
Specifies the parent widget ID
.IP "\fIname\fP" 10
Specifies the name of the created widget
.IP "\fIarglist\fP" 10
Specifies the argument list
.IP "\fIargcount\fP" 10
Specifies the number of attribute/value pairs in the argument list
(\fIarglist\fP)
.PP
For a complete definition of MultiList and its associated resources, see
\fBXmMultiList\fP(3)\&.
.SH "RETURN"
.PP
Returns the MultiList widget ID\&.
.SH "RELATED"
.PP
\fBXmMultiList\fP(3)\&.
