#!/bin/csh

# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# Motif
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA

set TESTS_HOME = $cwd
set DIR_LIST_AUTO = 'Auto/lib/Common \
Auto/lib/Create/geometry \
Auto/lib/Create/instances \
Auto/lib/Create/other \
Auto/lib/Create/resources \
Auto/lib/Create/specific \
Auto/lib/Create/widgets \
Auto/lib/Create \
Auto/lib/Script \
Auto/lib/Synth/events \
Auto/lib/Synth/info \
Auto/lib/Synth/other \
Auto/lib/Synth/primitives \
Auto/lib/Synth \
Auto/lib/Util \
Auto/lib/Visual/visual \
Auto/lib/Visual/other \
Auto/lib/Visual \
Auto/lib \
Auto'

set DIR_LIST_MANUAL = 'Manual/lib/Common \
Manual/lib \
Manual'

set DIR_TEXT = 'Toolkit/Text/lib/Auto \
Toolkit/Text/lib/Manual \
Toolkit/Text/lib'

# Go to each automated test directory

foreach dir ($DIR_LIST_MANUAL)
        cd $TESTS_HOME/$dir
        echo "I am in " $cwd

	if (-e Makefile) then
		mv -f  Makefile Makefile.bak
	endif
	imake -DUseInstalled -DMANUAL -I$TESTS_HOME/../config/cf -TMotif.tmpl -TImake.tmpl -DTOPDIR=$TESTS_HOME/..
end
cd $TESTS_HOME/Manual && make -i

foreach dir ($DIR_LIST_AUTO)
        cd $TESTS_HOME/$dir
        echo "I am in " $cwd

	if (-e Makefile) then
	mv -f Makefile Makefile.bak
	endif
	imake -DUseInstalled -DAUTOMATIC -I$TESTS_HOME/../config/cf -TMotif.tmpl -TImake.tmpl -DTOPDIR=$TESTS_HOME/..
end

cd $TESTS_HOME/Auto && make -i

foreach dir ($DIR_TEXT)
        cd $TESTS_HOME/$dir
        echo "I am in " $cwd

	if (-e Makefile) then
	mv -f Makefile Makefile.bak
	endif
	imake -DUseInstalled -DAUTOMATIC -I$TESTS_HOME/../config/cf -TMotif.tmpl -TImake.tmpl -DTOPDIR=$TESTS_HOME/..
	make
end
