#!/bin/sh
# Motif
#
# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA
# 
# 
# HISTORY

if (test $# -lt 1)
then
        language=american
	testcase=a
else
        language=$1
	testcase=$2
fi

if [ -n "$(whence uname)" ]
then 
	sysname=`uname -s`
else
	sysname="unix"
fi

case $sysname in
	HP-UX | ULTRIX | OSF1 )
	echo Operating System is $sysname
	;;
	* )
	echo Operating System is unknown !!!
	echo You should update xmfile script to support your OS
	;;
esac

case $language in
  french)
        XAPPLRESDIR=`pwd`/french
	case $sysname in
	HP-UX)
		LANG=french.iso88591
		;;
	* )
		LANG=french
		;;
	esac
	;;

  english | american )
        XAPPLRESDIR=`pwd`/american
        case $sysname in
	HP-UX)
		LANG=american
		;;
	* )
		LANG=american
		;;
	esac
	;;

  hebrew)
        XAPPLRESDIR=`pwd`/hebrew
        case $sysname in
	HP-UX)
		LANG=hebrew
		;;
	* )
		LANG=hebrew
		;;
	esac
	;;

  japanese)
        XAPPLRESDIR=`pwd`/japanese
        case $sysname in
	HP-UX)
		LANG=japanese
		;;
	* )
		LANG=japanese
		;;
	esac
	;;

  japanese.euc)
        XAPPLRESDIR=`pwd`/japanese/euc
        case $sysname in
	HP-UX)
		LANG=japanese.euc
		;;
	* )
		LANG=japanese
		;;
	esac
	;;

  korean)
        XAPPLRESDIR=`pwd`/korean
        case $sysname in
	HP-UX)
		LANG=korean
		;;
	* )
		LANG=korean
		;;
	esac
	;;

  * )
	echo unknown language $language -- try running in C locale
        XAPPLRESDIR=`pwd`
	unset LANG
	;;	
esac

XFILESEARCHPATH=$XAPPLRESDIR/I18N.defaults:$XFILESEARCHPATH 

export XFILESEARCHPATH LANG XAPPLRESDIR

I18N1 -I $XAPPLRESDIR/I18N1$testcase.Dat -u $testcase
