#!/bin/csh
# Motif
#
# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA
#
# HISTORY

# 
#	This portion of the script will run the cutpaste2 test. Two
#	copies of the client cutpaste2a will be invoked.  This
#	will test cut/paste interaction between two clients.
#
cp Cutpaste2a Cutpaste2a1
cp Cutpaste2a Cutpaste2a2

Cutpaste2a1 -geometry +0+0 $* &
Cutpaste2a2 -geometry +0+200 $* &

Cutpaste2b $*

#
# Kill both copies of client cutpaste1a1
#

set PS_LINE1=`ps | grep Cutpaste2a1 | grep -v grep`
set PS_LINE2=`ps | grep Cutpaste2a2 | grep -v grep`

set PID1=`echo $PS_LINE1 | cut -d' ' -f1`
set PID2=`echo $PS_LINE2 | cut -d' ' -f1`

kill -9 $PID1
kill -9 $PID2

rm Cutpaste2a1
rm Cutpaste2a2

