#!/bin/csh
# Motif
#
# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA
#
# HISTORY

# 
#	This shell script will run the noninteractive Mrm tests FetchL
#	RegisterN, HierN and make FetchWloop.uid and redirect the output
#	to the file	'nonint.out'
#

if (-e nonint.out) then
	mv nonint.out nonint.out.bk
endif

echo ""
echo "Running the noninteractive Mrm tests FetchL, RegisterN, HierN and"
echo "	make FetchWloop.uid."
echo "Output will be redirected to the file nonint.out."

echo "These are the results of the noninteractive Mrm tests:" > nonint.out
echo "" >> nonint.out
echo "" >> nonint.out

echo "	."
echo >> nonint.out
echo "------------------------------------ FetchL ------------------------------------" >> nonint.out

FetchL $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "---------------------------------- RegisterN -----------------------------------" >> nonint.out

RegisterN $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "------------------------------------ HierN -------------------------------------" >> nonint.out

HierN $* >>& nonint.out 

echo "	."
echo >> nonint.out
echo "------------------------------- make FetchWloop.uid ---------------------------" >> nonint.out

#remove all other core files so later test works
echo "Removing any existing core files" >> nonint.out
if (-e core) then
   rm core
endif

../.././clients/uil/uil -o FetchWloop.uid FetchWloop.uil  -I../.././clients/uil  FetchWloop.uid >>& nonint.out 

set makestatus = $status

if ($makestatus == 1) then
   echo " " >> nonint.out
   echo "FetchWloop test PASSES" >> nonint.out
endif
if (($makestatus == 0) || (($makestatus <= 4) && ($makestatus > 1))) then
	echo "FetchWloop test FAILS" >> nonint.out
endif 
if ($makestatus > 4) then
  echo "FetchWloop test FAILS BADLY. " >> nonint.out
  if (-e core) then
   echo "A core file exists. This test may have died fatally." >> nonint.out
   echo "Please compile the file FetchWloop.uil manually." >> nonint.out
  endif
endif

echo " " >>& nonint.out
echo " " >>& nonint.out

echo "The noninteractive Mrm tests have completed."
echo ""

#
#  End Run script
#
