#!/bin/sh
# Motif
#
# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA
#
# HISTORY

# 
#	This shell script will run the interactive Mrm tests 
#	CloseH, FetchCL, FetchIL, FetchSV, FetchW, 
#	FetchWO, OpenH, and RegisterC.
#

echo ""
echo "Running the interactive Mrm tests "
echo "   CloseH, FetchCL, FetchIL, FetchSV, FetchW, "
echo "   FetchWO, OpenH, and RegisterC. "
echo "Summary output will be redirected to the file intsum.out."

echo "These are the results of the interactive Mrm tests:" > intsum.out
echo "" >> intsum.out
echo "" >> intsum.out

echo "	."
echo "------------------------------------ CloseH ------------------------------------" >> intsum.out

CloseH $* >> intsum.out

echo "	."
echo "------------------------------------ FetchCL ------------------------------------" >> intsum.out

FetchCL $* >> intsum.out

echo "	."
echo "------------------------------------ FetchIL ------------------------------------" >> intsum.out

FetchIL $* >> intsum.out

echo "	."
echo "------------------------------------ FetchSV ------------------------------------" >> intsum.out

FetchSV $* >> intsum.out

echo "	."
echo "------------------------------------ FetchW ------------------------------------" >> intsum.out

FetchW $* >> intsum.out

echo "	."
echo "------------------------------------ FetchWO ------------------------------------" >> intsum.out

FetchWO $* >> intsum.out

echo "	."
echo "------------------------------------ OpenH ------------------------------------" >> intsum.out
echo "This test sets the LANG environment variable to OpenHLang" >> intsum.out
set LANG=OpenHLang
OpenH $* >> intsum.out

echo "	."
echo "------------------------------------ RegisterC ------------------------------------" >> intsum.out

RegisterC $* >> intsum.out

echo "The interactive Mrm tests have completed."
echo ""

#
#  End Run script
#





