#!/bin/sh
# Motif
#
# Copyright (c) 1987-2012, The Open Group. All rights reserved.
#
# These libraries and programs are free software; you can
# redistribute them and/or modify them under the terms of the GNU
# Lesser General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# These libraries and programs are distributed in the hope that
# they will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with these librararies and programs; if not, write
# to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
# Floor, Boston, MA 02110-1301 USA
#
# HISTORY

CURR_MWM=../../../clients/mwm/mwm

SYSTEM=`uname -a | awk -F' ' '{print $1}'`

# print out error message

	case $# in
		0) echo "Usage : RunUITest [executable]" 
		exit
	esac


# print out warnings and question
	echo; echo
	echo "This is the execution script for the Mwm UI tests."
	echo
	echo "To begin this test, the window manager \"mwm\" will be"
	echo "killed and restarted with a new resource database."
        echo "You will then be asked to hit return when the new \"mwm\" is"
	echo "up and running.  Then, the actual test will be run, and upon"
	echo "completion, the original \"mwm\" will be restarted with it's"
	echo "original resource database intact."
	echo
	echo "It is assumed the original \"mwm\" running was ${TEST_MWM}," 
	echo "and, therefore, that is what will be restarted."
	echo

if [ ${SYSTEM} = "HP-UX" ] || [ ${SYSTEM} = "IRIX" ] 
then
# HP version
	echo "Do you want to continue? (n) \c"
else
# others, like DEC version
	echo "Do you want to continue? (n) "
fi

	read ANS
	ANS2=".${ANS}"
	if [ ${ANS2} != ".y" ]
	then
		echo "Cancelling test."
		exit
	fi



# merge in new resources into database
	xrdb -edit /tmp/oldxdef$$
	xrdb -load < $1."Xdefs"

# get the wm process and kill it
#	look for " mwm" or ".../mwm"
#	this should give you only things that really are mwm
#	remove all leading whitespace and replace multiple
#	tabs/spaces with 1 space
if [ ${SYSTEM} = "HP-UX" ] || [ ${SYSTEM} = "IRIX" ] 
then
# HP version
	MWM_LINE=`ps -ef | egrep ' mwm|/mwm' | grep -v egrep`
	BETTER_MWM_LINE=`echo ${MWM_LINE} | sed -e 's/^[	 ]*//
		s/[	 ][	 ]*/ /g'`
	MWM_PID=`echo ${BETTER_MWM_LINE} | cut -d' ' -f2`
	MWM_CMD=`echo ${BETTER_MWM_LINE} | cut -d' ' -f8-`
	MWM_OPTS=`echo ${BETTER_MWM_LINE} | cut -d' ' -f9-`
fi
if [ ${SYSTEM} = "OSF1" ] 
then
	MWM_LINE=`ps -a | egrep ' mwm|/mwm' | grep -v egrep`
	BETTER_MWM_LINE=`echo ${MWM_LINE} | sed -e 's/^[	 ]*//
		s/[	 ][	 ]*/ /g'`
	MWM_PID=`echo ${BETTER_MWM_LINE} | awk '{print $1}'`
	MWM_CMD=`echo ${BETTER_MWM_LINE} | cut -d' ' -f8-`
	MWM_OPTS=`echo ${BETTER_MWM_LINE} | cut -d' ' -f9-`
fi
if [ ${SYSTEM} = "SunOS" ] 
then
# others, like DEC version
    MWM_LINE=`ps axw | egrep ' mwm|/mwm' | grep -v egrep`
	BETTER_MWM_LINE=`echo ${MWM_LINE} | sed -e 's/^[   ]*//
		s/[  ][  ]*/ /g'`
	MWM_PID=`echo ${BETTER_MWM_LINE} | cut -d' ' -f1`
	MWM_CMD=`echo ${BETTER_MWM_LINE} | cut -d' ' -f5-`
	MWM_OPTS=`echo ${BETTER_MWM_LINE} | cut -d' ' -f6-`
fi

	kill -9 ${MWM_PID}


# start new wm and then start test
	${CURR_MWM} ${MWM_OPTS} >/dev/null 2>&1 &
	sleep 10

if [ ${SYSTEM} = "HP-UX" ] || [ ${SYSTEM} = "IRIX" ]
then
# HP version
	echo "Hit return after the new \"mwm\" is up and running. (CR) \c"
else
# others, like DEC version
	echo -n "Hit return after the new \"mwm\" is up and running. (CR) "
fi



if [ ${SYSTEM} = "HP-UX" ] || [ ${SYSTEM} = "IRIX" ] || [ ${SYSTEM} = "OSF1" ] 
then
# HP version
TEST_MWM_PID=`ps -eaf | egrep ' mwm|/mwm' | grep -v egrep | awk -F' ' '{print $2}'`
else
TEST_MWM_PID=`ps -axw | egrep ' mwm|/mwm' | grep -v egrep | awk -F' ' '{print $1}'`
fi

# now start the test program
	$1

# restore old resource database, kill new wm and restart old one
	echo "The original \"mwm\" is being restored..."


if [ -s /tmp/oldxdef$$ ]
then
	xrdb /tmp/oldxdef$$
else
	xrdb -remove	
fi


 kill -9 ${TEST_MWM_PID}
 ${CURR_MWM} ${MWM_OPTS}>/dev/null 2>&1 &
	sleep 10

	rm -f /tmp/oldxdef$$*

# end of script




