.\" $XConsortium: xmanimate.man /main/4 1995/07/17 10:46:33 drk $
.\" Motif
.\"
.\" Copyright (c) 1987-2012, The Open Group. All rights reserved.
.\"
.\" These libraries and programs are free software; you can
.\" redistribute them and/or modify them under the terms of the GNU
.\" Lesser General Public License as published by the Free Software
.\" Foundation; either version 2 of the License, or (at your option)
.\" any later version.
.\"
.\" These libraries and programs are distributed in the hope that
.\" they will be useful, but WITHOUT ANY WARRANTY; without even the
.\" implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
.\" PURPOSE. See the GNU Lesser General Public License for more
.\" details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with these librararies and programs; if not, write
.\" to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
.\" Floor, Boston, MA 02110-1301 USA
...\" 
...\" 
...\" HISTORY
.TH xmanimate 1X MOTIF "Demonstration programs"
.SH NAME
\*Lxmanimate\*O : an animation program using Motif
.SH SYNOPSIS
.sS
\*Lxmanimate\*O [-anim uidfile] [-speed speed_factor]
.sE
.SH DESCRIPTION
\*LXmanimate\*O
demonstrates the following Motif features:
     - declaration of icon/bitmap using UIL
     - exchange of value between UIL and C using Mrm.
     - use of the Motif form widget.
     - background procedure running while the client process
       is waiting for inputs (Xt intrinsics feature).
     
Xmanimate allows the user to animate a set of pixmaps in a window.
The pixmaps are not fixed by xmanimate but instead read at startup from
existing UID files. 

The syntax of all the 'animation.uid' files follows some simple rules and
one can easily add a new set of pixmaps to be animated using xmanimate.

dog.uil, plane.uil and superman.uil are tree examples of animation data 
files. (superman<N>.xbm are referenced in superman.uil). The default animation
is 'dog'. To run the demo with the other animations, use the command:

% xmanimate -anim plane

% xmanimate -anim superman

xmanimate.uil and xmanimate.c are the core components of the program.

speed_factor is a number between 0 and 100.


.SH Files
.nf
.ta 1.2i
XmdAnimate: the app-default file, which is very important for usability.
Try running something like: (XENVIRONMENT=XmdAnimate xmanimate) 

.fi
.SH X Defaults
The class of this application is \fIXmdAnimate\fR.  

.SH Editres: 
Xmanimate is Editres aware, so you can use 'editres' to see the
names of the widgets in the instance hierarchy.


